// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQL9AuNlJxknP395KdBHwgJEdug9v4X9E',
    appId: '1:908338806568:web:07594992da517d16ef1a1d',
    messagingSenderId: '908338806568',
    projectId: 'test-flutter-4aba2',
    authDomain: 'test-flutter-4aba2.firebaseapp.com',
    storageBucket: 'test-flutter-4aba2.appspot.com',
    measurementId: 'G-M62XF8H64G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3AoPpbNiuuDbLktJzJf8TEGj9S2Y-bd4',
    appId: '1:908338806568:android:fb53a7d63639919def1a1d',
    messagingSenderId: '908338806568',
    projectId: 'test-flutter-4aba2',
    storageBucket: 'test-flutter-4aba2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbq_U1EH7XapbnlUEqbHpctg_rzDFn-Vg',
    appId: '1:908338806568:ios:2a6f8b897efa9ee8ef1a1d',
    messagingSenderId: '908338806568',
    projectId: 'test-flutter-4aba2',
    storageBucket: 'test-flutter-4aba2.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbq_U1EH7XapbnlUEqbHpctg_rzDFn-Vg',
    appId: '1:908338806568:ios:2a6f8b897efa9ee8ef1a1d',
    messagingSenderId: '908338806568',
    projectId: 'test-flutter-4aba2',
    storageBucket: 'test-flutter-4aba2.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQL9AuNlJxknP395KdBHwgJEdug9v4X9E',
    appId: '1:908338806568:web:d447e098047b6e5eef1a1d',
    messagingSenderId: '908338806568',
    projectId: 'test-flutter-4aba2',
    authDomain: 'test-flutter-4aba2.firebaseapp.com',
    storageBucket: 'test-flutter-4aba2.appspot.com',
    measurementId: 'G-FQDJ9SYKFB',
  );
}
